name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci

    #- name: Install fonts
     # run: |
     #   sudo apt-get install -y fonts-liberation
     #   sudo apt-get install -y ttf-mscorefonts-installer
          
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' 

    - name: List files in the repository
      run: ls -R

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./KraftKollen/KraftKollen/KraftKollen.csproj

    # Build the Blazor app
    - name: Build the app
      run: dotnet build ./KraftKollen/KraftKollen/KraftKollen.csproj --configuration Release

      # Publish the app (for Blazor WebAssembly or Server App)
    - name: Publish the app
      run: dotnet publish ./KraftKollen/KraftKollen/KraftKollen.csproj --configuration Release --output ./published

    # Start the app (for Blazor Server or WebAssembly)
    - name: Start Blazor app
      run: |
        nohup dotnet ./published/KraftKollen.dll > app_output.log 2>&1 &
        sleep 10 # Give the app some time to start

    - name: Wait for the app to start
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5000/ | grep -q '<h3>Select a Year</h3>'; then
            echo "App is up!"
            break
          fi
          echo "Waiting for app to start..."
          sleep 3
        done

    - name: Check app output to confirm the port
      run: |
        tail -n 50 app_output.log  # Display the last 50 lines of the app output to check for the port


    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
