name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' 

    - name: List files in the repository
      run: ls -R

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./KraftKollen/KraftKollen/KraftKollen.csproj

    # Build the Blazor app
    - name: Build the app
      run: dotnet build ./KraftKollen/KraftKollen/KraftKollen.csproj --configuration Release

      # Publish the app (for Blazor WebAssembly or Server App)
    - name: Publish the app
      run: dotnet publish ./KraftKollen/KraftKollen/KraftKollen.csproj --configuration Release --output ./published

    # Start the app (for Blazor Server or WebAssembly)
    - name: Start Blazor app
      run: |
        nohup dotnet ./published/KraftKollen.dll &
        sleep 10 # Give the app some time to start
      
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
