name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      # Start Blazor app using the .NET image and expose the required port
      web:
        image: mcr.microsoft.com/dotnet/aspnet:8.0
        ports:
          - 5057:80
        options: --health-cmd="curl --fail http://localhost:80/health" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Restore and Build Blazor App
      run: |
        # Install .NET SDK
        curl -sSL https://aka.ms/getdotnet | bash
        dotnet --version
        
        # Restore and build Blazor app
        dotnet restore
        dotnet build

    - name: Run Blazor app
      run: |
        dotnet run --urls http://0.0.0.0:5057 &  # Run the Blazor app on port 5057
        # Wait for the app to start up
        sleep 10  # Adjust this sleep time if necessary, or check for health
      
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
